# Generated by Django 3.2.25 on 2025-04-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_table',
            name='emotion_score',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotion_table',
            name='movement',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
