# Generated by Django 3.2.25 on 2025-04-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250409_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion_table',
            old_name='movement',
            new_name='movementdown',
        ),
        migrations.AddField(
            model_name='emotion_table',
            name='movementleft',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotion_table',
            name='movementright',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emotion_table',
            name='movementup',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
