# Generated by Django 3.2.25 on 2025-04-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20250409_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_table',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table'),
        ),
    ]
