# Generated by Django 3.2.25 on 2025-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_emotion_table_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_table',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
