# Generated by Django 5.2 on 2025-05-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_emotion_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion_table',
            name='attention_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotion_images/'),
        ),
        migrations.AddField(
            model_name='student_table',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_attentive', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attendance_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student_table')),
            ],
        ),
    ]
